# -*- coding: utf-8 -*-
"""Data Steam Analyst.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17xd5u24ngyPq1s_u-kXaX9dyGrrkyHpa

# **0. BACA DATA**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('steam.csv')
data

"""#**1. Menentukan tipe game berdasarkan rating yang positif.**
Ditampilkan sebagai berikut:
"""

dataframe = data
baru1 = pd.DataFrame(dataframe, columns=['genres', 'positive_ratings', 'negative_ratings'])
baru1

baru2 = baru1.sort_values(by=['positive_ratings'], ascending=False)
baru3 = baru2.groupby(['genres']).sum()
baru3

sum_column = baru3["positive_ratings"] + baru3["negative_ratings"]
baru3["Total"] = sum_column
persenan = baru3["positive_ratings"] / baru3["Total"] * 100
baru3["Rating_Positive_@persen"] = persenan
baru3.sort_values(by=['Total'], ascending=False)
baru4 = baru3.sort_values(by=['Total'], ascending=False)
baru4

baru4 = pd.DataFrame(baru3, columns=['Total','Rating_Positive_@persen'])
baru5 = baru4.sort_values(by=['Rating_Positive_@persen'], ascending=False)
baru5

baru5 = baru4.sort_values(by=['Rating_Positive_@persen'], ascending=False)
baru5.head(5)

"""#**2. Menentukan publisher terbaik berdasarkan rata-rata waktu bermain.**
Ditampilkan sebagai berikut:
"""

play = pd.DataFrame(dataframe, columns=['genres', 'average_playtime', 'median_playtime'])
play

play['average_playtime'] = play['average_playtime'].astype(float)
play['median_playtime'] = play['median_playtime'].astype(float)
play

play1 = pd.DataFrame(play, columns=['genres', 'average_playtime', 'median_playtime'])
play1

play2 = play1.groupby(['genres']).sum()
play2

play3 = play2.sort_values(by=['average_playtime'], ascending=False)
play3

topp10 = play3.head(10)
topp10

topp5 = play3.head(5)
topp5

topp5.plot(kind="barh", fontsize=10, colormap='Paired')

"""#**3. Menentukan tipe game yang paling banyak dibeli.**
Ditampilkan sebagai berikut:
"""

beli = pd.DataFrame(dataframe, columns=['genres', 'owners', 'price'])
beli

beli['owners'] = beli['owners'].str.replace('-',' ')
beli

beli[['RentangAwal','RentangAkhir']] = beli.owners.str.split(expand=True)
beli

beli['RentangAwal'] = pd.to_numeric(beli['RentangAwal'])
beli['RentangAkhir'] = pd.to_numeric(beli['RentangAkhir'])
beli['price'] = pd.to_numeric(beli['price'])
beli

beli1 = beli.groupby(['genres']).mean()
beli1

beli2 = pd.DataFrame(beli1, columns=['price', 'RentangAkhir'])
beli2

final = beli2.sort_values(by=['RentangAkhir'], ascending=False)
final['Pembeli'] =  final['RentangAkhir']
final['Harga'] = final['price']
final1 = pd.DataFrame(final, columns=['Harga', 'Pembeli'])
final1

"""**START DARI SINI**

Tipe Game Berdasarkan Kategori Harga Termahal
"""

final2 = final1.sort_values(by=['Harga'], ascending=False)
final2

topp5 = final2.head(5)
topp5

top5 = pd.DataFrame(topp5.head(5), columns=['Pembeli'])
top5.plot(kind="barh", fontsize=10, colormap='Wistia_r')
plt.xlim(10000, 35000)

"""Time Game Berdasarkan Harga Tidak Berbayar atau Gratis"""

gratis = final1[final1.Harga==0]
gratis.sort_values(by=['Pembeli'], ascending=False)

topp7=gratis.head(7)
topp7

top7 = pd.DataFrame(gratis.head(7), columns=['Pembeli'])
top7.plot(kind="barh", fontsize=10, colormap='Wistia_r')
plt.xlim(3000000, 30000000)

"""Tipe Game Dengan Pembeli Terbanyak Berdasarkan Harga Berbayar"""

terbanyak = final1[final1.Harga>0]
terbanyak1 = terbanyak.sort_values(by=['Pembeli'], ascending=False)
terbanyak1.reset_index()

import seaborn as sns
graf = terbanyak1.drop(terbanyak1.index[0])
sns.scatterplot(data = graf, x='Harga', y = 'Pembeli', legend='auto', label='Plot Pembeli Terbanyak Kategori Berbayar')
plt.grid()
plt.xlim(0, 200)
plt.ylim(0.0, 2750000)

terbanyak

topp6 = terbanyak.head(6)
topp6

"""Jumlah Pembeli Terbanyak Berdasarkan Rentang Harga """

bins = [0, 5, 10, 20, 50, 180]
bagi = pd.cut(terbanyak['Harga'], bins, right=True)
bagi

bagi1 = pd.value_counts(bagi)
bagi1

rentang1 = terbanyak.iloc[:,:2][terbanyak.Harga>0][terbanyak.Harga<=5]
rentang2 = terbanyak.iloc[:,:2][terbanyak.Harga>5][terbanyak.Harga<=10]
rentang3 = terbanyak.iloc[:,:2][terbanyak.Harga>10][terbanyak.Harga<=20]
rentang4 = terbanyak.iloc[:,:2][terbanyak.Harga>20][terbanyak.Harga<=50]
rentang5 = terbanyak.iloc[:,:2][terbanyak.Harga>50][terbanyak.Harga<=180]

rentang1.loc['1-5', 'Pembeli'] = rentang1.Pembeli.sum()
rentang2.loc['6-10', 'Pembeli'] = rentang2.Pembeli.sum()
rentang3.loc['11-20', 'Pembeli'] = rentang3.Pembeli.sum()
rentang4.loc['21-50', 'Pembeli'] = rentang4.Pembeli.sum()
rentang5.loc['51-180', 'Pembeli'] = rentang5.Pembeli.sum()

satu = pd.DataFrame(rentang1, index=['1-5'], columns=['Pembeli'])
dua = pd.DataFrame(rentang2, index=['6-10'], columns=['Pembeli'])
tiga = pd.DataFrame(rentang3, index=['11-20'], columns=['Pembeli'])
empat = pd.DataFrame(rentang4, index=['21-50'], columns=['Pembeli'])
lima = pd.DataFrame(rentang5, index=['51-180'], columns=['Pembeli'])
rentang_harga = pd.concat([satu,dua,tiga,empat,lima], axis=0)
rentang_harga['Pembeli'] = rentang_harga['Pembeli'].astype(int)
rentang_harga

harga = rentang_harga.reset_index()
harga['Harga'] = harga['index']
harga1 = pd.DataFrame(harga, columns=['Harga', 'Pembeli'])
harga1['Pembeli'] = harga1['Pembeli'].astype(float)
harga1

plot = rentang_harga.plot(kind="barh", fontsize=10, colormap='Wistia_r')
plot.legend(loc=(0.38,-0.30),title = 'Harga',ncol=len(rentang_harga.columns))
plt.xlim(0, 52500000)

persen = harga1['Pembeli']
label = harga1['Harga']

plt.pie(persen, labels = label, autopct='%1.1f%%', shadow=False, startangle=15)
plt.show()